### ISSUE TITLE
Fatal error in FilterGroup

### ISSUE THREAD

**Issue by bognerf** [avadaneidanut/ldapquery#2]
Trying to use your library like described in Readme, the following fatal error is thrown

Fatal error: Arrays are not allowed in class constants in /home/bof09595/temp/ldaptiger/vendor/avadaneidanut/ldapquery/src/FilterGroup.php on line 19

My system: Linux, PHP5.5.32, CLI

**Comment by danutavadanei** [comment]
I didn't specify min php version. You have to use version > 5.6.\* for this
to work.
